
class Phase:
	counter = 0;
	UNREACHABLE_BLOCK = 1;
	ATTRIBUTES = 2;
	IN_OUT = 3;
	INHERITANCE = 4;
	PHI = 5;
	IMMEDIATE_DOMINATOR = 6;
	OPTIMIZE = 7;
	SUPERFICAL_CRUCIALITY = 8;
	BLOCK_CRUCIALITY = 9;
	INSTRUCTION_CRUCIALITY = 10;
	DEAD_CODE_REMOVAL = 11;
	EMPTY_BLOCK_REMOVAL = 12;

from .init import Phase_init;

Phase.__init__ = Phase_init;

